-- Generated by scripts/seed/build_seeds_from_notion.py.
-- Source: Notion 'LỊCH HẸN' / 'Loại dịch vụ khám' select options.
-- code = ASCII-upper-underscore of name (***# prefix stripped).
-- name = Notion option name verbatim.
-- Re-runnable: ON CONFLICT (code) DO NOTHING.

BEGIN;

INSERT INTO service_type (code, name, default_duration_minutes) VALUES
  ('SAN_1', 'Sản 1', 30),  -- notion option_id=5889d151-186f-47ad-9f39-880396dbc5c1
  ('SAN_2', 'Sản 2', 30),  -- notion option_id=d44bf50d-1f02-48dd-9340-3c4924085f63
  ('SAN_3', 'Sản 3', 30),  -- notion option_id=4ccec153-4f61-4db4-b806-2853e4cc8258
  ('NPDH', 'NPĐH', 30),  -- notion option_id=f361089c-85c8-4a3e-8d7b-18d0a8ee913e
  ('HO_SO_SINH', 'Hồ sơ sinh', 30),  -- notion option_id=370ee78e-a188-4419-846f-036daf8cc251
  ('TIEN_HON_NHAN', 'Tiền hôn nhân', 30),  -- notion option_id=ba074608-06f0-416f-9b60-35758999125c
  ('HIEM_MUON', 'Hiếm muộn', 30),  -- notion option_id=14b1571b-ecd1-46d3-857f-26f5e87995bb
  ('NOI_TIET_TINH_DUC', 'Nội tiết - Tình dục', 30),  -- notion option_id=6f17cdf0-d4f9-4f4c-bbe9-d2d4a18ca321
  ('PHU_KHOA', 'Phụ khoa', 30),  -- notion option_id=ba973716-6d33-4fff-a572-53de928ff3ea
  ('NAM_KHOA', 'Nam khoa', 30),  -- notion option_id=6a3d938d-e87a-427c-b36c-3d647d21b1c3
  ('TU_VAN_CHUYEN_SAU', 'Tư vấn chuyên sâu', 30),  -- notion option_id=dcfa8b6a-6cde-46ed-80e1-3ded83e4002c
  ('THU_THUAT', '***#Thủ thuật', 30),  -- notion option_id=c4f8aae5-83e4-43e6-93a2-9d9c3c5b8669
  ('FREE', 'FREE', 30),  -- notion option_id=1383a3cd-818f-417f-aa5f-e377ac14d362
  ('KHAM_TIEN_SAN', 'Khám tiền sản', 30)  -- notion option_id=e38204f0-219c-4381-89c6-fb7bbb05f6a6
ON CONFLICT (code) DO NOTHING;

COMMIT;
