-- Generated by scripts/seed/build_seeds_from_notion.py.
-- Source: Notion 'lib 3 - danh sách nhân viên' rows (master pages filtered out).
-- primary_department mapping rules: see _classify_dept in generator.
-- short_name = full_name with 'BS '/'BS SA ' prefix stripped.
-- primary_location_id = NULL (Notion 'Vị trí ưa thích' empty for all).
-- Re-runnable: each INSERT guarded by IF NOT EXISTS on full_name.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Nghị') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Nghị', 'Nghị', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 36dccb0e-ac88-8378-a2fb-8108711a5510
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Quyết') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Quyết', 'Quyết', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 581ccb0e-ac88-8395-8701-8155dd0e1778
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Thuận') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Thuận', 'Thuận', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 580ccb0e-ac88-83d7-88c6-817a494dbe7d
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Thiệp') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Thiệp', 'Thiệp', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 87bccb0e-ac88-82e4-946b-81fa0c6d3f7a
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Vân') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Vân', 'Vân', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 18bccb0e-ac88-82ad-8927-81bc26d47e85
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Thủy') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Thủy', 'Thủy', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 61dccb0e-ac88-820f-8446-8135cf2c2461
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Hùng') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Hùng', 'Hùng', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 803ccb0e-ac88-8342-9f7b-81003e92ec67
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Nam') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Nam', 'Nam', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 3a5ccb0e-ac88-8224-8e61-814031361eac
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Tiến') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Tiến', 'Tiến', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion b70ccb0e-ac88-835b-a290-817b48520925
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Hoàng') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Hoàng', 'Hoàng', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 898ccb0e-ac88-8315-9b01-01981d4984a0
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Minh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Minh', 'Minh', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 69accb0e-ac88-82c4-adc1-01525a315f03
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Dương Trang') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Dương Trang', 'ĐD Dương Trang', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 5d8ccb0e-ac88-8234-92af-818b464baebb
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Đạt') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Đạt', 'Đạt', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 497ccb0e-ac88-8245-86f2-01f740bd415e
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Trang Lê') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Trang Lê', 'ĐD Trang Lê', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion a2fccb0e-ac88-83c4-91ad-017f11409c66
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Bá Linh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Bá Linh', 'Bá Linh', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion e9accb0e-ac88-831a-b48b-81a377fa5170
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Hà Vũ') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Hà Vũ', 'ĐD Hà Vũ', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 768ccb0e-ac88-8288-ba07-81a4902a9eec
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Hằng') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Hằng', 'Hằng', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 3a1ccb0e-ac88-820a-881a-81e707de4b6a
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'TL Vân Anh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'TL Vân Anh', 'TL Vân Anh', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 6ccccb0e-ac88-83b0-9ed6-8155756ec67b
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Thành') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Thành', 'Thành', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 33bccb0e-ac88-83ca-bea8-811446124186
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Phương Anh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Phương Anh', 'ĐD Phương Anh', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 38bccb0e-ac88-83fb-89e9-8163847ac7d5
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS Linh Nam khoa') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS Linh Nam khoa', 'Linh Nam khoa', 'DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 4c4ccb0e-ac88-8291-b74a-01641b13d1e5
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Thủy Tiên') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Thủy Tiên', 'ĐD Thủy Tiên', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion e60ccb0e-ac88-82f3-9633-01a2f4b1be87
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Quỳnh Anh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Quỳnh Anh', 'ĐD Quỳnh Anh', 'RECEPTION', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 4a6ccb0e-ac88-83ec-86fc-811a19666cb7
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'Kiều Thủy') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'Kiều Thủy', 'Kiều Thủy', 'CSKH', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 66fccb0e-ac88-8227-a811-017a1e72a7d9
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Huế') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Huế', 'ĐD Huế', 'RECEPTION', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 075ccb0e-ac88-82dc-8645-81ee6a86254c
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'Kim Tiến') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'Kim Tiến', 'Kim Tiến', 'CSKH', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 635ccb0e-ac88-8328-a442-017b40f2f3cc
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Hải Yến') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Hải Yến', 'ĐD Hải Yến', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 2cdccb0e-ac88-8326-87ec-01fac2f44d65
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'Huyền Diệu') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'Huyền Diệu', 'Huyền Diệu', 'CSKH', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 10eccb0e-ac88-83a4-bf7b-813f521435a1
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'Diệu Hoa') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'Diệu Hoa', 'Diệu Hoa', 'CSKH', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion b52ccb0e-ac88-8319-b591-81d4772d839a
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'TL Duy Nam') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'TL Duy Nam', 'TL Duy Nam', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion c51ccb0e-ac88-8275-b50c-818f69c3473f
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Hương Linh') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Hương Linh', 'ĐD Hương Linh', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 2c9ccb0e-ac88-82ba-ae5a-01beae6ec763
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Thanh Hải') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Thanh Hải', 'ĐD Thanh Hải', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 82accb0e-ac88-82cd-9ab6-01682e339d0b
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Giầu') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Giầu', 'ĐD Giầu', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 857ccb0e-ac88-839c-b7e1-812227a597b5
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Thư') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Thư', 'ĐD Thư', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 346ccb0e-ac88-826f-904a-81e698f29858
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Hằng') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Hằng', 'ĐD Hằng', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 490ccb0e-ac88-82e8-ad8a-81bdfe74bae1
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Thanh An') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Thanh An', 'ĐD Thanh An', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 116ccb0e-ac88-83dc-b0a4-8134c8aa2f12
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Diễm Thúy') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Diễm Thúy', 'ĐD Diễm Thúy', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 1daccb0e-ac88-82df-8c67-81e229924bd4
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'ĐD Hà Phạm') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'ĐD Hà Phạm', 'ĐD Hà Phạm', 'NURSE_ULTRASOUND', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion f7dccb0e-ac88-834a-9263-01dbf51ac361
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'BS SA Giáp') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'BS SA Giáp', 'Giáp', 'ULTRASOUND_DOCTOR', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion b3fccb0e-ac88-8277-aef1-0116fa8bed26
  END IF;
  IF NOT EXISTS (SELECT 1 FROM staff WHERE full_name = 'Trang A') THEN
    INSERT INTO staff (id, full_name, short_name, primary_department, primary_location_id, employment_type, is_training, is_active) VALUES (gen_random_uuid(), 'Trang A', 'Trang A', 'CSKH', NULL, 'FULL_TIME', FALSE, TRUE);  -- notion 239ccb0e-ac88-83ac-80a1-0124d63c71ea
  END IF;
END
$$;

COMMIT;
